FROM golang:1.22

# Install OpenCV + dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    libopencv-dev \
    pkg-config

# Set GoCV env
ENV CGO_ENABLED=1

WORKDIR /app

# Install GoCV
RUN go install gocv.io/x/gocv/cmd/version@latest