# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/inference.proto\x12\tinference\"I\n\x0c\x46rameRequest\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0c\x12\x11\n\tcamera_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"=\n\x0b\x42oundingBox\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\"\x83\x01\n\tDetection\x12\x10\n\x08track_id\x18\x01 \x01(\x05\x12\x12\n\nclass_name\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12$\n\x04\x62\x62ox\x18\x04 \x01(\x0b\x32\x16.inference.BoundingBox\x12\n\n\x02\x63x\x18\x05 \x01(\x02\x12\n\n\x02\x63y\x18\x06 \x01(\x02\"d\n\x11\x44\x65tectionResponse\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12(\n\ndetections\x18\x02 \x03(\x0b\x32\x14.inference.Detection\x12\x12\n\nlatency_ms\x18\x03 \x01(\x03\x32S\n\x10InferenceService\x12?\n\x06\x44\x65tect\x12\x17.inference.FrameRequest\x1a\x1c.inference.DetectionResponseB3Z1github.com/sharm/anomaly-platform/proto/inferenceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/sharm/anomaly-platform/proto/inference'
  _globals['_FRAMEREQUEST']._serialized_start=36
  _globals['_FRAMEREQUEST']._serialized_end=109
  _globals['_BOUNDINGBOX']._serialized_start=111
  _globals['_BOUNDINGBOX']._serialized_end=172
  _globals['_DETECTION']._serialized_start=175
  _globals['_DETECTION']._serialized_end=306
  _globals['_DETECTIONRESPONSE']._serialized_start=308
  _globals['_DETECTIONRESPONSE']._serialized_end=408
  _globals['_INFERENCESERVICE']._serialized_start=410
  _globals['_INFERENCESERVICE']._serialized_end=493
# @@protoc_insertion_point(module_scope)
